/*
Copyright (c) 2026 - present, Ephraim Neuberger. All rights reserved.

The code and materials provided by Ephraim Neuberger are for non-commercial testing and evaluation purposes only.
Ephraim Neuberger reserves all rights not expressly granted.

Any permitted copy must retain this copyright notice and disclaimer.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL EPHRAIM NEUBERGER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef _WPP_GUIDS_INCLUDED_
#define _WPP_GUIDS_INCULDED_

#ifndef IS_GUID
#define IS_GUID(a)
#endif

#ifndef DEFINE_WPP_GUIDS
#define DEFINE_WPP_GUIDS 1
#endif

#if DEFINE_WPP_GUIDS==1

#define SECURITY_LAB_DRV 1960B51C, DB03, 4472, A3F6, B5912827375F
//{1960B51C-DB03-4472-A3F6-B5912827375F}

#define SECURITY_LAB_COVERITY_TEST 2ED1A99E, CEBD, 42AE, 93B9, 607915D195D1
//{2ED1A99E-CEBD-42AE-93B9-607915D195D1}


#endif //DEFINE_WPP_GUIDS==1





IS_GUID(SECURITY_LAB_DRV)


#endif //_WPP_GUIDS_INCLUDED_
