/*
Copyright (c) 2026 - present, Ephraim Neuberger. All rights reserved.

The code and materials provided by Ephraim Neuberger are for non-commercial testing and evaluation purposes only.
Ephraim Neuberger reserves all rights not expressly granted.

Any permitted copy must retain this copyright notice and disclaimer.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL EPHRAIM NEUBERGER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef THIS_GUID
#define THIS_GUID 0,0,0,0,0
#endif

#ifndef WPP_FRIENDLY_NAME
#error WPP_FRIENDLY_NAME must be defined
#endif


#define WPP_CONTROL_GUIDS \
    WPP_DEFINE_CONTROL_GUID(WPP_FRIENDLY_NAME, (THIS_GUID), \
	WPP_DEFINE_BIT(DBG_INFO) \
	WPP_DEFINE_BIT(DBG_DEBUG) \
	WPP_DEFINE_BIT(DBG_WARNING) \
	WPP_DEFINE_BIT(DBG_ERROR) \
	WPP_DEFINE_BIT(DBG_CRITICAL) \
	WPP_DEFINE_BIT(DBG_EXCEPTION) \
	WPP_DEFINE_BIT(DBG_CONSOLE) \
	WPP_DEFINE_BIT(DBG_TRACE_FUNCTIONS) \
	WPP_DEFINE_BIT(DBG_BREAK) \
)

#if 0
// added here to aid the intelisence
#define ESL_DBG_OUT()

#define DBG_INFO 0x1
#define DBG_DEBUG 0x2
#define DBG_WARNING 0x4
#define DBG_ERROR 0x8
#define DBG_CRITICAL 0x10
#define DBG_EXCEPTION 0x20
#define DBG_CONSOLE 0x40
#define DBG_TRACE_FUNCTIONS 0x80
#define DBG_BREAK 0x100

#endif
