#pragma once


#define SEC_LAB_SERVER_PORT_NAME L"\\Lpc_SEC_LAB_Port"

typedef struct _LPC_SEC_LAB_SERVER_MESSAGE64
{
	LPC_BASIC_MESSAGE64 BasicMessage;
	WCHAR Text[64];

} LPC_SEC_LAB_SERVER_MESSAGE64, * PLPC_SEC_LAB_SERVER_MESSAGE64;

